#!/bin/sh

protected_branch="main"
current_branch=$(git symbolic-ref --short HEAD)

if [ "$protected_branch" = "$current_branch" ]; then
  echo "Өөрийн нэртэй branch үүсгэнэ үү. Жишээ: git checkout -b e.erkhem"
  exit 1
fi

exit 0
